---
- name: Add {{item.name}} repository
  template: dest=/etc/yum.repos.d/{{item.name}}.repo src=ca_cert.repo.j2

- name: Install {{item.name}} CA certificates
  yum: name={{item.packages}} state=latest enablerepo={{item.name}}
